### ISSUE TITLE
Reporter incorrectly destructured from onRenderBody

### ISSUE THREAD

**Issue by mixja** [hutsoninc/gatsby-plugin-hubspot#49]
See https://github.com/hutsoninc/gatsby-plugin-hubspot/blob/master/src/gatsby-ssr.js#L5

As per https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody there is no `reporter` available.

This causes following error on this [line](https://github.com/hutsoninc/gatsby-plugin-hubspot/blob/master/src/gatsby-ssr.js#L15) when HubSpot tracking code is not defined:

`WebpackError: TypeError: Cannot read property 'warn' of undefined`

**Comment by AustinLeeGordon** [comment]
@mixja Thanks for pointing that out! I'll make that fix really quick.
