### ISSUE TITLE
js.hsforms.net wasn't loaded

### ISSUE THREAD

**Issue by wiadev** [hutsoninc/gatsby-plugin-hubspot#6]
Hi.

I've installed the plugin today but `js.hsforms.net` script wasn't loaded at all when I check on network tab.

Here is my gatsby-config.

```
require("dotenv").config();

module.exports = {
    plugins: [
        {
            resolve: "gatsby-plugin-hubspot",
            options: {
                trackingCode: process.env.HUBSPOT_PORTAL_ID,
            },
        },
        `gatsby-plugin-emotion`,
        `gatsby-plugin-no-sourcemaps`,
        `gatsby-plugin-react-helmet`,
        `gatsby-plugin-catch-links`,
        `gatsby-plugin-sass`,
        `gatsby-plugin-typescript`,
        `gatsby-plugin-meta-redirect`,
        {
            resolve: `gatsby-plugin-sitemap`,
            options: {
                exclude: [`/ironcore-cmk/*`],
            },
        },
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `src`,
                path: `${__dirname}/src/`,
            },
        },
        {
            resolve: `gatsby-transformer-remark`,
            options: {
                classPrefix: `language-js`,
                plugins: [`gatsby-remark-prismjs`, `gatsby-remark-external-links`],
            },
        },
        {
            resolve: "gatsby-source-graphql",
            options: {
                typeName: "TS",
                fieldName: "takeshape",
                url: `https://api.takeshape.io/project/${process.env.TAKESHAPE_PROJECT}/graphql`,
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${process.env.TAKESHAPE_TOKEN}`,
                },
                fetchOptions: {},
            },
        }        
    ],
};
```

Any thoughts on this?

Thanks

**Comment by AustinLeeGordon** [comment]
@wiadev are you looking it in production or development? It won't be loaded in during development.

**Comment by MarkRich** [comment]
@AustinLeeGordon is there a recommended way to test this during development then? just want to make sure the pages views and such are coming through before committing.

**Comment by AustinLeeGordon** [comment]
@MarkRich If you're using something like Netlify for hosting, you should be able to create a deploy preview from a pull request or separate branch and see the scripts being loaded.

**Comment by wiadev** [comment]
@AustinLeeGordon I'm looking at it in development. Is there any way to check in development locally?

**Comment by AustinLeeGordon** [comment]
@MarkRich @wiadev We can add an option that will allow the script to render in development, but I don't think page views will get sent to HubSpot on a local development server. You would at least be able to check if the scripts are rendering. How does that sound?

**Comment by wiadev** [comment]
@AustinLeeGordon Sounds great!
I need to load the hubspot form on local but since it's not loading the hsscripts, I couldn't create a form, FYI.

**Comment by AustinLeeGordon** [comment]
@wiadev @MarkRich Gotcha! We don't use the HubSpot forms on our site, so I hadn't come across that yet. Just added a `productionOnly` option in v1.3.0. Update to that version and set `productionOnly` to `false` in the plugin options and you should be good to go! Let me know if everything works okay and I'll close this issue.

**Comment by wiadev** [comment]
Thanks @AustinLeeGordon It works like a charm.

I have another question. I'm building the project in typescript and since hbspt is global variable, it shows hbspt as an error.

![Screen Shot 2019-06-21 at 1 03 09 AM](https://user-images.githubusercontent.com/18234060/59907639-67716780-93c0-11e9-8ecb-27254289f30d.png)

So I put the `declare var hbspt: any;` at the top to resolve this but on build time, I've got the undefined hbspt error.

![Screen Shot 2019-06-21 at 1 04 31 AM](https://user-images.githubusercontent.com/18234060/59907698-8d970780-93c0-11e9-85d7-e92532bb236b.png)

Do you have any suggestions?

**Comment by AustinLeeGordon** [comment]
@wiadev Awesome, thanks for the update!

I've only used TypeScript a little, so I'm not exactly sure about that. Try some of the suggestions in these SO threads:

- https://stackoverflow.com/questions/12703266/how-to-handle-warnings-for-proprietary-custom-properties-of-built-in-objects-in/12703866#12703866
- https://stackoverflow.com/questions/12709074/how-do-you-explicitly-set-a-new-property-on-window-in-typescript

**Comment by wiadev** [comment]
Thanks.
